"use client";

import type { Metadata } from "next";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Header from "@/app/components/Header/Header";

import styles from "./layout.module.scss";
import "./globals.scss";

type Props = {
  children: React.ReactNode;
};

  // export const metadata: Metadata = {
  //   title: "Create Next App",
  //   description: "Generated by create next app",
  // };

const queryClient = new QueryClient();

const RootLayout = ({ children }: Props) => {
  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en">
        <body>
          <Header />
          <main className={styles["main"]}>{children}</main>
        </body>
      </html>
    </QueryClientProvider>
  );
};

export default RootLayout;
